server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://j7b305.p.ssafy.io:8761/eureka
      #defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user-service/**
            - Method=GET,POST,PUT,DELETE
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/auth-service/(?<segment>.*),/$\{segment}

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth-service/**
            - Method=GET,POST,PUT,DELETE
        #          filters:
        #            - RemoveRequestHeader=Cookie
        #            - RewritePath=/auth-service/(?<segment>.*),/$\{segment}

        - id: interest-service
          uri: lb://INTEREST-SERVICE
          predicates:
              - Path=/api/interest-service/**
              - Method=GET,POST,PUT,DELETE
        #          filters:
        #            - RemoveRequestHeader=Cookie
        #            - RewritePath=/auth-service/(?<segment>.*),/$\{segment}

        - id: festival-service
          uri: lb://FESTIVAL-SERVICE
          predicates:
            - Path=/api/festival-service/**
            - Method=GET,POST,PUT,DELETE
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/auth-service/(?<segment>.*),/$\{segment}

        - id: game-service
          uri: lb://GAME-SERVICE
          predicates:
            - Path=/api/game-service/**
            - Method=GET,POST,PUT,DELETE
        #          filters:
        #            - RemoveRequestHeader=Cookie
        #            - RewritePath=/auth-service/(?<segment>.*),/$\{segment}

        - id: recomm-service
          uri: lb://RECOMM-SERVICE
          predicates:
            - Path=/api/recomm-service/**
            - Method=GET,POST,PUT,DELETE
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/auth-service/(?<segment>.*),/$\{segment}

        - id: log-service
          uri: lb://LOG-SERVICE
          predicates:
            - Path=/api/log-service/**
            - Method=GET,POST,PUT,DELETE
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/auth-service/(?<segment>.*),/$\{segment}
