server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: j7b305.p.ssafy.io
    port: 5672
    username: guest
    password: guest


management:
  endpoints:
    web:
      exposure:
        include: busrefresh