spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://j7b305.p.ssafy.io:3306/jeonwoochi?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #url: jdbc:mysql://localhost:3306/jeonwoochi_user?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #  ?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    #username: root
    #password:
    username: b305
    password: B305user!
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
    generate-ddl: true

token:
  access_token:
    expiration_time: 86400000
  refresh_token:
    expiration_time: 604800000
  secret:
