server:
  port: 0
  error:
    whitelabel:
      enabled: false
  servlet:
    # TODO : CONTEXT-PATH가 해당 서비스명과 같은지 확인
    context-path: /api/user-service
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true

spring:
  application:
    name: user-service

  zipkin:
    # TODO : 서버에 Open Zipkin Jar 파일 다운로드 후 실행하면 연결됨
    base-url: http://127.0.0.1:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: busrefresh